export const CHART_CONFIG = {
  AGE_LABEL_WIDTH: 100,
  YEAR_COLUMN_WIDTH: 16,
  Y_AXIS_WIDTH: 80,
  CHART_RIGHT_MARGIN: 30,
  MIN_CHART_WIDTH: 560,
  BAR_CATEGORY_GAP: 0,
  BAR_GAP: '-100%',
  CHART_MARGIN_TOP: 20,
  CHART_MARGIN_BOTTOM: 0,
} as const;

export const CHART_LEFT_MARGIN =
  CHART_CONFIG.AGE_LABEL_WIDTH - CHART_CONFIG.Y_AXIS_WIDTH;
